# Generated by Django 6.0.4 on 2026-04-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_favorite_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='dietary_tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.dietarytag'),
        ),
    ]
