# Generated by Django 6.0.4 on 2026-04-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_dietarytag_recipe_dietary_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Calories per serving', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbs',
            field=models.PositiveIntegerField(blank=True, help_text='Carbs (g) per serving', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.PositiveIntegerField(blank=True, help_text='Fat (g) per serving', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.PositiveIntegerField(blank=True, help_text='Protein (g) per serving', null=True),
        ),
    ]
